### ISSUE TITLE
Question: How does it know what language your file is in?

### ISSUE THREAD

**Issue by Unsure23** [juj/vs-tool#23] opened 2013-10-31 15:39 UTC
I'm playing around with Emscripten to make a simple triangle render on screen via shaders. My first step was to render it as a win32 application (it does) and now I'm trying to alter my code so it still works as a win32 application (awesome if I can, if not, oh well) but being able to compile it with Emscripten.

I'm using Visual Studio 2010 to code/compile. I am coding in C++ and I have a file for utility functions (insofar it only holds a single function that reads what's in a file and stores it into a string). The file structure is C-ish, it's a file with a function; but I'm also using C++ strings, streams, namespaces, etc so it's definitely a C++ source file (complete with .cpp file extension). However, when I compile it thinks it's a C source file (when I echo the command line it uses '-x c') and I get the error: GCCCOMPILE : error : invalid argument '-std=c++03' not allowed with 'C/ObjC'

So my question is how does it "know" what language the file is so it can specify it in the command line? I've changed my code so rather than a function in a file it's a dumby class' method just to see if it parses the file for any language specifics, tried adding a try/catch and other C++ things, but it still uses C as the language. I've tried adding '-x c++' to the command line, but it still adds '-x c' and it's further in the command so it overwrites my C++ declaration and I get the same error. It knows my other files are C++ but seems to keep wanting to think this file is C.

I've copied the command to the command prompt and changed it to use C++ and it seems to work (I get compile errors, which is great because it seems to actually be trying to compile then rather than go 'oops, can't do it').

**_Edit**_
Also I forgot to mention, my code is structured so that there is a 'main' source file that has the int main function. It is a .cpp file as well, has no header and is a single function (much like utility function file, except the utility function file has a header file) and it detects that it is C++. I'm trying to see what the difference between the two are, but an explanation of how it determines the language will definitely help. Thanks.

**_Edit**_
Also, I have the 'Language Standard Mode' as 'Not set (default to gnu99')'. If I change it to a C language then it chokes on my C++ files (no surprise) and if I select a C++ language it chokes on my utility function file since it thinks it's a C file.

**Comment by Unsure23** [comment] 2013-11-04 16:51
Oooooookay, it looks like I found the issue and it's strange. If the file is in a folder with a space in it (IE: Utility Functions) it tries to compile it as a C source file. If the file is in a folder without a space (UtilityFunctions, Utility_Functions, etc) then it compiles it as C++.

So my next question is, why?

**Comment by juj** [comment] 2013-11-04 16:59
Can you make a small standalone zipped visual studio solution+project package that reproduces the issue? I can give it a look then.

**Comment by Unsure23** [comment] 2013-11-04 22:01
I've made the zip file but I'm new to github so I don't know how to give it to you.

**Comment by juj** [comment] 2013-11-04 22:26
Github does not unfortunately allow attachments, so you need to use some other means of transferring the file. I recommend using dropbox, that's how I store all github-related files that I want to link to in bug reports.

**Comment by Unsure23** [comment] 2013-11-05 16:14
Awesome. So I've tried accessing the dropbox website and its blocked. I asked around and apparently any code written in the office is company property and is to never leave the premises. (Makes me wonder about backups....) So basically I am not allowed to provide you the test code I'm using.

Luckily however, the issue should be easy enough to replicate. Open an existing C++ project, add a C++ source file to a folder with a space in it (it can be an empty source file), add the file to the project and compile.

**Comment by juj** [comment] 2013-11-07 22:34
Thanks for reporting, this is fixed now in commit https://github.com/juj/vs-tool/commit/da26fca896a62d4d68cd5bfac910fcf858976287 . The issue was due to a failure with path quoting when there are spaces.

**Closed as completed by juj** 2013-11-07 22:34 UTC
