### ISSUE TITLE
Link problem with emscripten tool chain

### ISSUE THREAD

**Issue by ghost** [juj/vs-tool#4] opened 2013-01-19 13:55 UTC
I'm trying to build emscripten/tests/msvc10, but for all projects the link fails and I can't understand why.
I am running Windows 7 family on a laptop
Installed CLANG / LLVM prebuild from Mingw-w64.
All the compile steps works correcly, and link step works fine when called manually from shell as : 
c:/python27/python.exe C:/Projets/GitHub/emscripten/emcc Emscripten/helloc_world_c_Debug/hello_world.o -o Emscripten/Debug/hello_world_c.html
but when called by Visual Studio, this step fails.
I even rewrite in C++ the emcc.exe tool but got exactly the same issue !
All ideas welcome !

Stephane

**Comment by juj** [comment] 2013-01-21 13:14
Thanks for reporting!

I have not tested prebuilt clang/llvm. What is the issue you get? What is the output (and error messages) printed? Emscripten now requires llvm+clang version 3.2, older versions are no longer supported. You can check the version from command line with 'clang --version'.

**Comment by ghost** [comment] 2013-01-21 14:10
Clang --version gives:

clang version 3.2 (tags/RELEASE_32/final)
Target: x86_64-w64-mingw32
Thread model: posix

And "link" error message is : 

1>  System.ComponentModel.Win32Exception (0x80004005): Descripteur non valide
1>     à System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>     à System.Diagnostics.Process.Start()
1>     à pythonemcc.Program.Main(String[] args) dans C:\Projets\GitHub\vs-tool\pythonemcc\Program.cs:ligne 77
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(121,5): error MSB6006: "emcc.exe" exited with code 1.

Here the error message is in french, I suppose it's something like "Invalid Handle" in english.

Another info : I've used "Python 2.7.3 Windows X86-64 Installer" from python.org. It seems I don't get the same error using Python 32 bits. I will post another message with Python 32bits output.

Stéphane

**Comment by ghost** [comment] 2013-01-21 14:29
really weird
with 32bits python 2.7.3 installed I have the following for the link step :

 Launch c:\python27\python.exe with command line C:\Projets\GitHub\emscripten\emcc Emscripten/glbook_10_MultiTexture_Debug/MultiTexture.o Emscripten/glbook_10_MultiTexture_Debug/esShader.o Emscripten/glbook_10_MultiTexture_Debug/esShapes.o Emscripten/glbook_10_MultiTexture_Debug/esTransform.o Emscripten/glbook_10_MultiTexture_Debug/esUtil.o -o C:/Projets/GitHub/emscripten/tests/msvc10/Emscripten/Debug/glbook_10_MultiTexture.html
1>  
1>  shared.Building.is_bitcode failed to test whether file 'Emscripten/glbook_10_MultiTexture_Debug/MultiTexture.o' is a llvm bitcode file! Failed on exception: [Error 6] Descripteur non valide
1>  emcc: Emscripten/glbook_10_MultiTexture_Debug/MultiTexture.o: warning: Not valid LLVM bitcode
1>  shared.Building.is_bitcode failed to test whether file 'Emscripten/glbook_10_MultiTexture_Debug/esShader.o' is a llvm bitcode file! Failed on exception: [Error 6] Descripteur non valide
1>  emcc: Emscripten/glbook_10_MultiTexture_Debug/esShader.o: warning: Not valid LLVM bitcode
1>  shared.Building.is_bitcode failed to test whether file 'Emscripten/glbook_10_MultiTexture_Debug/esShapes.o' is a llvm bitcode file! Failed on exception: [Error 6] Descripteur non valide
1>  emcc: Emscripten/glbook_10_MultiTexture_Debug/esShapes.o: warning: Not valid LLVM bitcode
1>  shared.Building.is_bitcode failed to test whether file 'Emscripten/glbook_10_MultiTexture_Debug/esTransform.o' is a llvm bitcode file! Failed on exception: [Error 6] Descripteur non valide
1>  emcc: Emscripten/glbook_10_MultiTexture_Debug/esTransform.o: warning: Not valid LLVM bitcode
1>  shared.Building.is_bitcode failed to test whether file 'Emscripten/glbook_10_MultiTexture_Debug/esUtil.o' is a llvm bitcode file! Failed on exception: [Error 6] Descripteur non valide
1>  emcc: Emscripten/glbook_10_MultiTexture_Debug/esUtil.o: warning: Not valid LLVM bitcode
1>  emcc: no input files
1>  note that input files without a known suffix are ignored, make sure your input files end with one of: ('.c', '.cpp', '.cxx', '.cc', '.bc', '.o', '.obj', '.dylib', '.so', '.dll', '.a', '.ll')
1>  glbook_10_MultiTexture.vcxproj -> C:\Projets\GitHub\emscripten\tests\msvc10\Emscripten\Debug\glbook_10_MultiTexture.html
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

but again, if i open a Windows Shell, go to GitHub\emscripten\tests\msvc10
and launch the same command line :

c:\python27\python.exe C:\Projets\GitHub\emscripten\emcc Emscripten/glbook_10_MultiTexture_Debug/MultiTexture.o Emscripten/glbook_10_MultiTexture_Debug/esShader.o Emscripten/glbook_10_MultiTexture_Debug/esShapes.o Emscripten/glbook_10_MultiTexture_Debug/esTransform.o Emscripten/glbook_10_MultiTexture_Debug/esUtil.o -o C:/Projets/GitHub/emscripten/tests/msvc10/Emscripten/Debug/glbook_10_MultiTexture.html

the html file is generated without error...

**Comment by ghost** [comment] 2013-01-23 08:57
Some news :
one of my colleague made a shell script to do all the steps described in the wiki to setup Emscripten + vs-tools. The script successfully installed everything on Windows 8 Pro.
The same script used by another colleague on Windows 7 Ultimate install everything but at the end, he got exactly the same issues than mine. So the fact I used precompiled LLVM/CLANG seems not to be related to this issue.

**Comment by landona** [comment] 2013-01-30 10:37
It seems I have the same problem here: Followed the wiki instructions exactly (built llvm myself and all that) and get the following output within VS10 (Windows 7, 64bit):

1>------ Build started: Project: hello_world_c, Configuration: Debug Emscripten ------
1>  hello_world.c
1>  shared.Building.is_ar failed to test whether file 'Emscripten/hello_world_c_Debug/hello_world.d' is a llvm archive file! Failed on exception: [Errno 2] No such file or directory: 'Emscripten/hello_world_c_Debug/hello_world.d'
1>  shared.Building.is_ar failed to test whether file 'c' is a llvm archive file! Failed on exception: [Errno 2] No such file or directory: 'c'
1>  Exception received when starting tool 'c:\python27\python.exe' with command line 'F:\Emcc\emscripten\emcc Emscripten/hello_world_c_Debug/hello_world.o -o F:/Emcc/emscripten/tests/msvc10/Emscripten/Debug/hello_world_c.html'!
1>  System.ComponentModel.Win32Exception (0x80004005): The handle is invalid
1>     at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
1>     at System.Diagnostics.Process.Start()
1>     at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
1>     at pythonemcc.Program.Main(String[] args)
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(121,5): error MSB6006: "emcc.exe" exited with code 1.

Re-typing and executing the command by hand works.

**Comment by juj** [comment] 2013-03-14 17:52
This issue may be caused by having 64-bit node installed. Visual Studio is a 32-bit process, and it fails to spawn 64-bit processes. You can try uninstalling 64-bit node and reinstalling 32-bit node to test if that might help.

**Comment by ghost** [comment] 2013-03-15 07:08
thank you juj,

finallly everybody in our team have migrate to Windows 8 as we did not met this issue on this OS. Perhaps landona will be able to test your solution on Windows 7.

**Comment by zephon82** [comment] 2013-04-10 13:02
I had the exact same issue.

I've fixed it by re-installing python 2.7.4: i guess i had a 64bit version first, and it has been replaced by a 32bit version.

Now it seems to work fine.

**Comment by juj** [comment] 2014-01-03 12:01
Let me close this as fixed. A very recent commit fixes one "Handle is invalid" issue I was seeing. Please reopen if the issue still persists in the latest master, thanks!

**Closed as completed by juj** 2014-01-03 12:01 UTC
Labels: Platform:Emscripten
