### ISSUE TITLE
emscripten "hello_world_c" demo build fails in Visual Studio

### ISSUE THREAD

**Issue by codemonkey-uk** [juj/vs-tool#15] opened 2013-08-14 10:05 UTC
Hi

I am able to build the project from the command line. From within visual studio, it fails, with the following in the build log output:

1>------ Build started: Project: hello_world_c, Configuration: Debug Emscripten ------
1>  hello_world.c
1>  
1>  C:\git\emscripten\tests\msvc10>python C:\git\emscripten\emcc @"C:\Users\thaddaeus_frogley\AppData\Local\Temp\27b288083d634b08a504285124f15531.rsp" 
1>clang : warning : argument unused during compilation: '-nostdinc++'
1>  
1>  C:\git\emscripten\tests\msvc10>python C:\git\emscripten\emcc @C:\Users\thaddaeus_frogley\AppData\Local\Temp\557ac38d77984abb8a77ce8e48008401.rsp 
1>  The system cannot execute the specified program.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(121,5): error MSB6006: "emcc.bat" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

It looks to me like the compile step works, but the link step doesn't, and the different appears to be that the compile step wraps the path to the RSP in double quotes.

MS Visual Studio V.10.0.40219.1.SP1Rel
Python2.7

EDIT added info, with Emcc Linker/General/Echo Command Lines (YES), I get this:

1>------ Build started: Project: hello_world_c, Configuration: Debug Emscripten ------
1>  C:\git\emscripten\emcc.bat Emscripten/hello_world_c_Debug/hello_world.o -o C:/git/emscripten/tests/msvc10/Emscripten/Debug/hello_world_c.html
1>  
1>  C:\git\emscripten\tests\msvc10>python C:\git\emscripten\emcc @C:\Users\thaddaeus_frogley\AppData\Local\Temp\de509be565624fa0a1975b4357a6db44.rsp 
1>  The system cannot execute the specified program.
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(121,5): error MSB6006: "emcc.bat" exited with code 1.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

If I run the command reported in the output from the command line (cmd.exe) the link works and produces a working hello_world_c.html:

C:\git\emscripten\emcc.bat Emscripten/hello_world_c_Debug/hello_world.o -o C:/git/emscripten/tests/msvc10/Emscripten/Debug/hello_world_c.html

**Comment by juj** [comment] 2013-08-14 13:33
Perhaps this is a problem with the response files. If you place the command line parameters to a response file .rsp like shown in the second command 'python C:\git\emscripten\emcc @C:\Users\thaddaeus_frogley\AppData\Local\Temp\de509be565624fa0a1975b4357a6db44.rsp' and invoke it then from the command line, does it work?

**Comment by codemonkey-uk** [comment] 2013-08-14 14:11
If I create a file "test.rsp" containing:

> Emscripten/hello_world_c_Debug/hello_world.o 
> -o C:/git/emscripten/tests/msvc10/Emscripten/Debug/hello_world_c.html

Then (from the command line, working directory as solution directory) run:

> python C:\git\emscripten\emcc @test.rsp

The build completes with a working hello world html.

**Comment by MarkCallow** [comment] 2013-08-15 00:36
I am having this exact problem and have spent the last 2 weeks investigating it without success. It is a complete showstopper for me and I am on the point of giving up on Emscripten because of it.

It is unrelated to the response file contents or how the file name is quoted. If you replace the command in emcc.bat with simply "python -V" you get the same "The system cannot execute the specified program" error, hereafter the "9020 error" after its exit status.

As far as I can tell it is related to using the 32-bit version of Tracker.exe to execute the 64-bit version of python.

[If I use the 32-bit version of python instead, the link command begins to execute but python then exits with a "The handle is invalid" error. I believe this is a bug in python truncating a 64-bit Windows handle to 32-bit then passing it back to Windows. Issue #4 describes the same issue. There the reporter said that the problem went away after re-installing Python 2.7.4. It did not work for me. So I went back to investigating issue with 64-bit python.]

What is Tracker.exe? It is a tool used by MSBuild during the link to in some way track incremental files. I think MSBuild launches the build command by way of it. It is found in the Windows SDK at e.g. C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\bin\NETFX 4.0 Tools{,\x64}.  It is the only difference in the execution environment of the link phase compared to that of the successful compile phase.

I have tried the following to get MSBuild to run the 64-bit version without success:
- Set NativeExecutablePath like is done in Microsoft.Cpp.x64.v100.props
- Set the _IsNativeEnvironment environment variable
- Changed any macro I see in the projects properties sheet that refers to NETFX 4.0 Tools to point at the x64 folder
- Changed HKCU¥Software¥Microsoft¥VisualStudio¥10.0¥ExternalTools¥ToolDir2 to point at the x64 folder

Even with all of the above MSBuild is still using the 32-bit Tracker. How do I know? (a) I get the same 9020 error and (b) if I remove the 32-bit Tracker.exe the error changes to:

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Emscripten\Microsoft.Cpp.Emscripten.Targets(121,5): error MSB6001: Invalid command line switch for "emcc.bat". The resource string "Error.MissingFile" for the "GCCLink" task cannot be found. Confirm that the resource name "Error.MissingFile" is correctly spelled, and the resource exists in the task's assembly.

juj, have you ever run a successful link of one of the msvc10 test projects on Windows 7 64-bit? It looks to me to be completely broken and to only work on 32-bit Windows.

As noted above, this bug is a deal breaker. Please help me resolve it.

**Comment by MarkCallow** [comment] 2013-08-15 00:39
The fact that somebody from the UK is seeing the same problem rules out another of my theories - that this problem is related to my use of the Japanese version of Windows 7 - as, presumably, the OP is using an English version.

**Comment by juj** [comment] 2013-08-15 05:04
I run a laptop with Windows 7 Home Premium 64-bit OS, and building the emscripten tests solution with MSVC10 does succeed here.

If it helps, my installed software versions:
VS2010: 10.0.40219.1 SP1Rel

Python:
04/10/2012  11:31 PM            26,624 python.exe
Python 2.7.3
which seems to be a 32-bit executable.

MSBuild /ver:
Microsoft (R) Build Engine Version 4.0.30319.1
[Microsoft .NET Framework, Version 4.0.30319.1008]
Copyright (C) Microsoft Corporation 2007. All rights reserved.

4.0.30319.1

Have you tried running 32-bit version of Python?

**Comment by codemonkey-uk** [comment] 2013-08-15 09:00
Yes, my issue was on English, 64 bit Windows 7.

**Comment by MarkCallow** [comment] 2013-08-15 18:20
@juj 

> Have you tried running 32-bit version of Python?

Yes. See the 4th 'graph of my comment.

**Comment by codemonkey-uk** [comment] 2013-08-16 08:29
> Have you tried running 32-bit version of Python?

This changes the error for me:

1>------ Build started: Project: hello_world_c, Configuration: Debug Emscripten ------
1>  C:\git\emscripten\emcc.bat Emscripten/hello_world_c_Debug/hello_world.o -o C:/git/emscripten/tests/msvc10/Emscripten/Debug/hello_world_c.html
1>  
1>  C:\git\emscripten\tests\msvc10>python C:\git\emscripten\emcc @C:\Users\thaddaeus_frogley\AppData\Local\Temp\9f7b1b3797804680938eeef0882e4f1e.rsp 
1>GCCLINK : error root: 
1>  subprocess.Popen(args=c:\mingw64\bin\llvm-nm /tmp\tmpfc_9aw\hello_world_0.o) failed! Exception [Error 6] The handle is invalid
1>  
1>  Traceback (most recent call last):
1>    File "C:\git\emscripten\emcc", line 1379, in <module>
1>      symbolses = map(lambda temp_file: shared.Building.llvm_nm(temp_file), temp_files)
1>    File "C:\git\emscripten\emcc", line 1379, in <lambda>
1>      symbolses = map(lambda temp_file: shared.Building.llvm_nm(temp_file), temp_files)
1>    File "C:\git\emscripten\tools\shared.py", line 1037, in llvm_nm
1>      output = Popen([LLVM_NM, filename], stdout=stdout, stderr=stderr).communicate()[0]
1>    File "C:\git\emscripten\tools\shared.py", line 52, in **init**
1>      raise e
1>  WindowsError: [Error 6] The handle is invalid
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by juj** [comment] 2013-08-16 08:33
Is llvm-nm a 64-bit executable? Can you try replacing that with a 32-bit version?

**Comment by juj** [comment] 2013-08-16 10:56
Perhaps these are relevant to this issue? https://github.com/kripken/emscripten/issues/1520 and https://github.com/kripken/emscripten/issues/1530

**Comment by MarkCallow** [comment] 2013-08-16 15:05
The error described by codemonkey-uk in his recent comment is exactly the problem I was describing in the 4th 'graph of my initial comment. (I wish this issues tracker would number the comments.)

**Comment by MarkCallow** [comment] 2013-08-17 02:26
I built the 32-bit llvm/clang following the directions you linked to in issue #17.

I got 522 instances of the following error at the end of the llvm/clang build

>  CUSTOMBUILD : error : program not executable [C:\Users\callow_mark\projects\llvm-build\test\check-llvm.vcxproj]
> but the tools all seemed to have been built so I tried building an Emscripten test project: hello_world_gles

It built!  No errors. However when I ran it,  it failed to create a canvas.

Avoid the 64-bit tools at all cost! I did some further investigation but still have no clue what the issue is when using them.

**Comment by juj** [comment] 2014-01-03 11:01
A recent commit adds support for 64-bit tools on VS2010, however some things I noticed is that you cannot mix 32-bit and 64-bit toolchains (32-bit python + 64-bit Clang), or that Handle is invalid error appears, and tracking incremental builds for link output stages will not work, i.e. Visual Studio always insists on relinking the project again and again even if nothing was changed. I'll close this issue as resolved. Have a go at updating to the latest to see if it works for you.

**Closed as completed by juj** 2014-01-03 11:01 UTC

**Comment by subchannel13** [comment] 2014-03-15 19:54
This is closed for some time but I'd like to point a solution that worked for me with x64 Emscripten installation:

https://go4answers.webhost4life.com/Example/hello-world-does-not-compile-vs2010-ide-2015.aspx

Idea is to not use Tracker.exe. It can be achieved by adding <TrackFileAccess>false</TrackFileAccess> in <PropertyGroup> in project file (.vcxproj).

**Comment by subchannel13** [comment] 2014-03-15 20:00
Markdown cropped XML tags :(. What I wanted to say was (replace normal brackets with angled):

It can be achieved by adding (TrackFileAccess)false(/TrackFileAccess) in (PropertyGroup) in project file (.vcxproj).

**Comment by juj** [comment] 2014-03-16 15:10
The TrackFileAccess workaround is known, but it has the unfortunate effect of making VS always do full rebuilds, so it was rejected as a solution. The vs-tool trunk has preparatory code for a better solution in the plugin level, but it's not quite ready yet. I'm hoping the next release to have that fixed up completely.

**Comment by subchannel13** [comment] 2014-03-16 19:35
Slow build is better then no build. Also what TrackFileAccess speeds up? I gathered it only tracks resources, .res files but I may be wrong there.

Anyway this workaround might be helpful for some people so it should at least be documented. For instance I intend to primarily build for Win32 and for Emscripten only occasionally. So, I can wait.
